# Generated by Django 4.1.1 on 2022-09-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('phone', models.BigIntegerField(default=0)),
                ('email', models.EmailField(default=None, max_length=39)),
                ('query', models.CharField(default=None, max_length=300)),
            ],
        ),
    ]
