# Generated by Django 4.1.1 on 2022-10-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default=None, max_length=111),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default=None, max_length=111),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(default=None, max_length=111),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_json',
            field=models.CharField(default=None, max_length=5000),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default=None, max_length=111),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default=None, max_length=111),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.CharField(default=None, max_length=111),
        ),
    ]
